### ISSUE TITLE
Not all events appear in the calendar

### ISSUE THREAD

**Issue by SalimNedjam** [AmineDjeghri/SUCAL#1]
Found that in the official website we have events that do not appear in SUCAL
Example: 
- m2 sar 12 October : official website has 3 events but not SUCAL

**Comment by AmineDjeghri** [comment]
okey, so i think i found the problem:
some events have rules like :  `RULE:FREQ=WEEKLY;INTERVAL=1;UNTIL=20210215T072959Z`
and the also they have some dates that are excluded from the rule like `EXDATE;TZID=Europe/Paris:20201221T083000`

**Comment by AmineDjeghri** [comment]
Fixed
