### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by naskio** [AmineDjeghri/SUCAL#3]
I would like to suggest a new feature that allows us to export the calendar (format **.ics**).

**Comment by AmineDjeghri** [comment]
Hello,
All the calendars are available here (adapt the URL to the appropriate master and it will automatically download the calendar)
https://cal.ufr-info-p6.jussieu.fr:443/caldav.php/

Example M1 STL (add /STL/M1_STL)
https://cal.ufr-info-p6.jussieu.fr:443/caldav.php/STL/M1_STL
USERNAME = "student.master"
PASSWORD = "guest"

Here is the file where you can view the URL
https://github.com/AmineDjeghri/SUCAL/blob/master/app/data/masters.yml

**Comment by naskio** [comment]
it works as charme,
thanks man.
